import { col } from "../db";
import { json } from "../lib/response";
import { serializeMany } from "../lib/id";

/**
 * Generate commission ledgers for all mentors for the previous quarter.
 * Mirrors base44/functions/generateQuarterlyLedgers/entry.ts.
 */
export async function generateQuarterlyLedgers(): Promise<Response> {
  const now = new Date();
  const currentMonth = now.getMonth();
  const currentYear = now.getFullYear();

  let prevQuarterNumber: number;
  let prevYear: number;
  if (currentMonth < 3) {
    prevQuarterNumber = 4;
    prevYear = currentYear - 1;
  } else if (currentMonth < 6) {
    prevQuarterNumber = 1;
    prevYear = currentYear;
  } else if (currentMonth < 9) {
    prevQuarterNumber = 2;
    prevYear = currentYear;
  } else {
    prevQuarterNumber = 3;
    prevYear = currentYear;
  }

  const quarterLabel = `${prevYear}-Q${prevQuarterNumber}`;
  const startMonth = (prevQuarterNumber - 1) * 3;
  const startDate = new Date(prevYear, startMonth, 1);
  const endDate = new Date(prevYear, startMonth + 3, 0);
  const startDateStr = startDate.toISOString().split("T")[0];
  const endDateStr = endDate.toISOString().split("T")[0];

  const allUsers = serializeMany(await col("users").find({}, { projection: { password_hash: 0 } }).toArray());
  const mentors = allUsers.filter((u: any) => ["junior_mentor", "senior_mentor"].includes(u.app_role));

  const allTransactions = serializeMany(await col("funding_transactions").find({}).toArray());
  const allAdjustments = serializeMany(await col("manual_commission_adjustments").find({}).toArray());
  const existingLedgers = serializeMany(await col("commission_ledgers").find({}).toArray());

  let createdCount = 0;
  let skippedCount = 0;

  for (const mentor of mentors) {
    const existing = existingLedgers.find((l: any) => l.mentor_id === mentor.id && l.quarter === quarterLabel);
    if (existing) {
      skippedCount++;
      continue;
    }
    const start = new Date(startDateStr);
    const end = new Date(endDateStr);
    end.setHours(23, 59, 59, 999);

    const relevant = allTransactions.filter((t: any) => {
      if (t.status !== "APPROVED") return false;
      const attributed = t.initiating_mentor_id || t.primary_mentor_id;
      if (attributed !== mentor.id) return false;
      const d = new Date(t.requested_at);
      return d >= start && d <= end;
    });

    // DEPOSIT and BONUS both feed into the mentor's commissionable net.
    const totalDeposits = relevant.filter((t: any) => t.type === "DEPOSIT" || t.type === "BONUS").reduce((s: number, t: any) => s + (t.amount_usd || 0), 0);
    const totalWithdrawals = relevant.filter((t: any) => t.type === "WITHDRAWAL").reduce((s: number, t: any) => s + (t.amount_usd || 0), 0);
    const netDeposit = totalDeposits - totalWithdrawals;

    const prevQuarterNum = prevQuarterNumber === 1 ? 4 : prevQuarterNumber - 1;
    const prevQuarterYear = prevQuarterNumber === 1 ? prevYear - 1 : prevYear;
    const prevQuarterLabel = `${prevQuarterYear}-Q${prevQuarterNum}`;
    const prevLedger = existingLedgers.find((l: any) => l.mentor_id === mentor.id && l.quarter === prevQuarterLabel);
    const bufferCarriedIn = prevLedger?.commission_buffer_usd || 0;

    const grossCommission = netDeposit * 0.04;
    const adjustmentTotal = allAdjustments
      .filter((a: any) => {
        if (a.mentor_id !== mentor.id) return false;
        // Attribute by effective_date (falls back to created_date for old rows).
        const d = new Date(a.effective_date || a.created_date);
        return d >= start && d <= end;
      })
      .reduce((s: number, a: any) => s + (a.amount_usd || 0), 0);
    // Last quarter's held buffer carries forward into adjusted gross, then splits
    // 75/25 into this quarter's release and buffer.
    const adjustedGross = grossCommission + adjustmentTotal + bufferCarriedIn;
    const commissionRelease = adjustedGross * 0.75;
    const commissionBuffer = adjustedGross * 0.25;
    const releaseDate = new Date(prevYear, startMonth + 3, 15);
    const releaseDateStr = releaseDate.toISOString().split("T")[0];

    const ledgerData = {
      mentor_id: mentor.id,
      mentor_name: mentor.full_name,
      quarter: quarterLabel,
      year: prevYear,
      quarter_number: prevQuarterNumber,
      start_date: startDateStr,
      end_date: endDateStr,
      net_deposit_usd: netDeposit,
      gross_commission_usd: grossCommission,
      manual_adjustment_usd: adjustmentTotal,
      adjusted_gross_commission_usd: adjustedGross,
      commission_release_usd: commissionRelease,
      commission_buffer_usd: commissionBuffer,
      buffer_carried_in_usd: bufferCarriedIn,
      buffer_carried_out_usd: commissionBuffer,
      is_closed: true,
      is_released: false,
      release_date: releaseDateStr,
      closed_by_id: "SYSTEM",
      closed_by_name: "Automated System",
      closed_at: new Date().toISOString(),
      notes: "Auto-generated by quarterly ledger automation",
      created_date: new Date().toISOString(),
      updated_date: new Date().toISOString(),
    };
    await col("commission_ledgers").insertOne(ledgerData as any);
    createdCount++;
  }

  return json({
    success: true,
    quarter: quarterLabel,
    period: `${startDateStr} to ${endDateStr}`,
    mentors_processed: mentors.length,
    ledgers_created: createdCount,
    ledgers_skipped: skippedCount,
    timestamp: new Date().toISOString(),
  });
}
