import React, { useState, useEffect, useMemo } from 'react';
import { base44 } from "@/api/base44Client";
import { useQuery } from "@tanstack/react-query";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { CheckCircle, XCircle } from "lucide-react";
import TagsPicker from "./TagsPicker";

const DEPOSIT_PAYMENT_METHODS = [
  'AED TRANSFER',
  'UPI',
  'CARD PAYMENT',
  'USDT',
  'INR TRANSFER',
  'Cash deposit',
  'Other'
];

const WITHDRAWAL_PAYMENT_METHODS = [
  'AED TRANSFER',
  'UPI',
  'CARD PAYMENT',
  'USDT',
  'INR TRANSFER',
  'Cash Withdrawal',
  'Bank Withdrawal',
  'Other'
];

export default function ProcessFundingDialog({ transaction, open, onClose, onProcess, currentUser }) {
  const [formData, setFormData] = useState({
    amount_usd: 0,
    payment_method: '',
    mt5_account_id: '',
    mt5_login: '',
    transaction_id: '',
    rejection_reason: '',
    notes: '',
    tags: [],
  });
  const [transactionIdError, setTransactionIdError] = useState('');
  const [withdrawalMentorId, setWithdrawalMentorId] = useState('');

  const { data: mt5Accounts = [] } = useQuery({
    queryKey: ['mt5accounts', transaction?.student_id],
    queryFn: async () => {
      if (!transaction?.student_id) return [];
      const accounts = await base44.entities.MT5Account.list();
      return accounts.filter(acc => acc.student_id === transaction.student_id);
    },
    enabled: !!transaction?.student_id && open
  });

  const { data: student, isLoading: isLoadingStudent } = useQuery({
    queryKey: ['student', transaction?.student_id],
    queryFn: async () => {
      if (!transaction?.student_id) return null;
      const students = await base44.entities.Student.list();
      return students.find(s => s.id === transaction.student_id);
    },
    enabled: !!transaction?.student_id,
    staleTime: 0
  });

  const { data: allTransactions = [] } = useQuery({
    queryKey: ['all-funding-transactions'],
    queryFn: () => base44.entities.FundingTransaction.list(),
    enabled: open
  });

  // Product catalog — used to recompute bundled products if a super admin
  // changes the product during approval.
  const { data: bonusTags = [] } = useQuery({
    queryKey: ['transaction-tags-catalog'],
    queryFn: async () => (await base44.entities.TransactionTag.list('name')).filter(t => t.active !== false),
    staleTime: 5 * 60_000,
  });

  // Commission credits generated by THIS transaction — who got paid, at what
  // level and how much (same breakdown as the Bonus/Deposit Commission reports).
  const { data: txCredits = [] } = useQuery({
    queryKey: ['tx-credits', transaction?.id],
    queryFn: () => base44.entities.CommissionCredit.filter({ transaction_id: transaction.id }),
    enabled: !!transaction?.id && open,
  });

  // Build co-managed mentor options for withdrawal attribution
  const coManagedMentorOptions = useMemo(() => {
    if (!student || !transaction || transaction.type !== 'WITHDRAWAL') return [];
    let coMentors = [];
    if (student.co_mentors_details) {
      try {
        coMentors = typeof student.co_mentors_details === 'string'
          ? JSON.parse(student.co_mentors_details)
          : student.co_mentors_details;
      } catch (_) {}
    }
    if (!Array.isArray(coMentors) || coMentors.length === 0) return [];
    const options = [{ id: student.primary_mentor_id, name: student.primary_mentor_name }];
    coMentors.forEach(cm => {
      if (!options.find(o => o.id === cm.mentor_id)) {
        options.push({ id: cm.mentor_id, name: cm.mentor_name });
      }
    });
    return options;
  }, [student, transaction]);

  const isCoManagedWithdrawal = coManagedMentorOptions.length > 0;

  useEffect(() => {
    if (transaction) {
      setFormData({
        amount_usd: transaction.amount_usd || 0,
        payment_method: transaction.payment_method || '',
        mt5_account_id: transaction.mt5_account_id || '',
        mt5_login: transaction.mt5_login || '',
        transaction_id: transaction.transaction_id || '',
        rejection_reason: transaction.rejection_reason || '',
        notes: transaction.notes || '',
        // Carry ALL existing tags through: tags[0] is the primary product and
        // tags[1..] are bundled products auto-included with it (kept for the record).
        tags: Array.isArray(transaction.tags) ? [...transaction.tags] : [],
      });
      setTransactionIdError('');
      setWithdrawalMentorId('');
    }
  }, [transaction]);

  const handleApprove = async () => {
    if (!formData.transaction_id || formData.transaction_id.trim() === '') {
      setTransactionIdError('Transaction ID is required');
      return;
    }
    // A sales-close bonus credit has no product (see the box below), so only other bonuses need one.
    if (transaction.type === 'BONUS' && !transaction.bonus_credit && (!formData.tags || formData.tags.length === 0)) {
      setTransactionIdError('Please pick a product for this bonus before approving');
      return;
    }

    const duplicate = allTransactions.find(
      t => t.transaction_id === formData.transaction_id && t.id !== transaction.id
    );
    
    if (duplicate) {
      setTransactionIdError('This Transaction ID already exists');
      return;
    }

    setTransactionIdError('');
    
    const selectedMT5Account = mt5Accounts.find(acc => acc.id === formData.mt5_account_id);
    
    const selectedWithdrawalMentor = isCoManagedWithdrawal && withdrawalMentorId
      ? coManagedMentorOptions.find(m => m.id === withdrawalMentorId)
      : null;

    const updatedData = {
      ...formData,
      mt5_login: formData.mt5_account_id ? (selectedMT5Account?.mt5_login || formData.mt5_login) : formData.mt5_login,
      initiating_mentor_id: transaction.type === 'WITHDRAWAL'
        ? (isCoManagedWithdrawal ? selectedWithdrawalMentor?.id : transaction.primary_mentor_id)
        : (transaction.initiating_mentor_id || undefined),
      initiating_mentor_name: transaction.type === 'WITHDRAWAL'
        ? (isCoManagedWithdrawal ? selectedWithdrawalMentor?.name : transaction.primary_mentor_name)
        : (transaction.initiating_mentor_name || undefined),
      status: 'APPROVED'
    };

    // Auto-upgrade student from Level 1 to Level 2 on first approved deposit
    if (transaction.type === 'DEPOSIT' && student?.student_level === 'LEVEL_1') {
      const previousApprovedDeposits = allTransactions.filter(
        t => t.student_id === transaction.student_id && t.type === 'DEPOSIT' && t.status === 'APPROVED' && t.id !== transaction.id
      );
      if (previousApprovedDeposits.length === 0) {
        await base44.entities.Student.update(transaction.student_id, { student_level: 'LEVEL_2' });
      }
    }
    // Update co_mentors_details via backend function
    console.log('initiating_mentor_id:', transaction.initiating_mentor_id, '| type:', transaction.type);
    if (transaction.type === 'DEPOSIT') {
      // Update co-mentor contribution if initiating mentor exists
      if (transaction.initiating_mentor_id) {
        try {
          await base44.functions.invoke('updateCoMentorContribution', {
            student_id: transaction.student_id,
            mentor_id: transaction.initiating_mentor_id
          });
        } catch (err) { console.error('Failed to update co-mentor contribution:', err); }
      }
      // Also update primary mentor's entry in co_mentors_details if they have one
      if (transaction.primary_mentor_id) {
        try {
          await base44.functions.invoke('updateCoMentorContribution', {
            student_id: transaction.student_id,
            mentor_id: transaction.primary_mentor_id
          });
        } catch (err) { console.error('Failed to update primary mentor contribution:', err); }
      }
    }

    // Withdrawal deductions for co-managed clients are handled via CoManageCalculator tool
    // No additional processing needed here

    onProcess(updatedData);
  };

  const handleReject = () => {
    const updatedData = {
      ...formData,
      status: 'REJECTED'
    };
    
    onProcess(updatedData);
  };

  if (!transaction) return null;

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Process Funding Request</DialogTitle>
        </DialogHeader>

        {/* A bonus Delta Finance approved: its payment is confirmed — credit the bonus in MT5, then approve. */}
        {transaction.type === 'BONUS' && transaction.status === 'PENDING' && transaction.finance_approval?.state === 'decided' && transaction.finance_approval?.decision === 'approved' && (
          <div className="rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm text-emerald-900">
            Delta Finance approved the payment{transaction.finance_approval.decided_by_name ? ` (${transaction.finance_approval.decided_by_name})` : ''}
            {transaction.transaction_id ? ` — transaction ID ${transaction.transaction_id}` : ''}.
            {transaction.course_payment?.bonus_usd ? ` Credit the $${transaction.course_payment.bonus_usd} MT5 bonus` : ' Credit the bonus'}
            {transaction.mt5_login ? ` in ${transaction.mt5_login}` : ''}, then approve.
            {transaction.finance_approval.note && <span className="block text-xs text-emerald-800">Accounts: {transaction.finance_approval.note}</span>}
          </div>
        )}

        <div className="space-y-4">
          <div className="bg-gray-50 rounded-lg p-4 space-y-2">
            <div className="grid grid-cols-2 gap-2 text-sm">
              <div>
                <span className="text-gray-600">Type:</span>
                <span className="ml-2 font-semibold">{transaction.type}</span>
              </div>
              <div>
                <span className="text-gray-600">Student:</span>
                <span className="ml-2 font-semibold">{transaction.student_name}</span>
              </div>
              <div>
                <span className="text-gray-600">Code:</span>
                <span className="ml-2 font-mono font-semibold">{transaction.student_code}</span>
              </div>
              <div>
                <span className="text-gray-600">Student Level:</span>
                <span className={`ml-2 font-semibold ${student?.student_level === 'LEVEL_1' ? 'text-yellow-700' : 'text-green-700'}`}>
                  {student?.student_level || 'Unknown'}
                </span>
              </div>
              <div className="col-span-2">
                <span className="text-gray-600">Meeting Conducted By:</span>
                <span className="ml-2 font-semibold">{transaction.meeting_mentor_name || '—'}</span>
              </div>
            </div>
          </div>

          <div className="space-y-2 bg-blue-50 p-4 rounded-lg border-2 border-blue-200">
            <Label htmlFor="amount_usd" className="text-base font-semibold">Amount (USD) - Editable</Label>
            <Input
              id="amount_usd"
              type="number"
              step="0.01"
              value={formData.amount_usd}
              onChange={(e) => setFormData({ ...formData, amount_usd: parseFloat(e.target.value) || 0 })}
              placeholder="Enter amount in USD"
              className="text-lg font-semibold"
            />
          </div>

          {/* The bonus promised at a sales close: raised with no product, and it earns no commission
              (backend creditCommission skips bonus credits) — nothing to pick, for anyone. */}
          {transaction.type === 'BONUS' && transaction.bonus_credit && (
            <div className="space-y-1 bg-violet-50 p-4 rounded-lg border-2 border-violet-200">
              <p className="text-base font-semibold">Sales-close bonus — no product needed</p>
              <p className="text-sm text-violet-900">
                Promised at the sales close
                {transaction.sales_close?.course ? ` (${transaction.sales_close.course}${transaction.sales_close.invoice_number ? `, invoice ${transaction.sales_close.invoice_number}` : ''})` : ''}.
                {' '}No commission on it — credit it in MT5, then approve.
              </p>
            </div>
          )}

          {/* Tag editor — visible only for BONUS transactions. Super admins can
              change the tag before approving; other roles see it read-only. */}
          {transaction.type === 'BONUS' && !transaction.bonus_credit && (
            <div className="space-y-2 bg-amber-50 p-4 rounded-lg border-2 border-amber-200">
              <Label className="text-base font-semibold">
                Product
                {currentUser?.app_role === 'super_admin'
                  ? <span className="ml-2 text-xs font-normal text-amber-700">(super admin can change before approval)</span>
                  : <span className="ml-2 text-xs font-normal text-gray-500">(only super admins can change this)</span>}
              </Label>
              {currentUser?.app_role === 'super_admin' ? (
                <TagsPicker
                  value={formData.tags}
                  onChange={(picked) => {
                    // Re-derive bundled products when the primary product changes.
                    const primary = picked[0];
                    const product = bonusTags.find(t => t.name === primary);
                    const included = Array.isArray(product?.includes)
                      ? product.includes.filter(n => n && n !== primary)
                      : [];
                    setFormData({ ...formData, tags: primary ? [primary, ...included] : [] });
                  }}
                />
              ) : (
                <p className="text-sm font-medium">
                  {formData.tags?.[0] || <span className="text-gray-500 italic">No product set</span>}
                </p>
              )}
              {formData.tags.length > 1 && (
                <p className="text-xs text-green-700 font-medium">
                  Includes (no extra charge): {formData.tags.slice(1).join(', ')}
                </p>
              )}
            </div>
          )}

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="payment_method">Payment Method</Label>
              <Select
                value={formData.payment_method}
                onValueChange={(value) => setFormData({ ...formData, payment_method: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select payment method" />
                </SelectTrigger>
                <SelectContent>
                  {(transaction?.type === 'WITHDRAWAL' ? WITHDRAWAL_PAYMENT_METHODS : DEPOSIT_PAYMENT_METHODS).map((method) => (
                    <SelectItem key={method} value={method}>
                      {method}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="mt5_account">MT5 Account</Label>
              <Select
                value={formData.mt5_account_id}
                onValueChange={(value) => setFormData({ ...formData, mt5_account_id: value })}
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select MT5 account" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={null}>None</SelectItem>
                  {mt5Accounts.map((account) => (
                    <SelectItem key={account.id} value={account.id}>
                      {account.mt5_login} ({account.platform})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="mt5_login">MT5 Login (Manual)</Label>
              <Input
                id="mt5_login"
                value={formData.mt5_login}
                onChange={(e) => setFormData({ ...formData, mt5_login: e.target.value })}
                placeholder="Or enter manually"
                disabled={!!formData.mt5_account_id}
              />
            </div>

            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="transaction_id">
                Transaction ID <span className="text-red-500">*</span>
              </Label>
              <Input
                id="transaction_id"
                value={formData.transaction_id}
                onChange={(e) => {
                  setFormData({ ...formData, transaction_id: e.target.value });
                  setTransactionIdError('');
                }}
                placeholder="Enter unique transaction ID"
                className={transactionIdError ? 'border-red-500' : ''}
              />
              {transactionIdError && (
                <p className="text-sm text-red-600">{transactionIdError}</p>
              )}
            </div>

            {isCoManagedWithdrawal && (
              <div className="space-y-2 md:col-span-2">
                <Label className="text-base font-semibold text-orange-700">Attribute Withdrawal To *</Label>
                <Select value={withdrawalMentorId} onValueChange={setWithdrawalMentorId}>
                  <SelectTrigger className="border-orange-300 focus:ring-orange-400">
                    <SelectValue placeholder="Select mentor to attribute withdrawal to" />
                  </SelectTrigger>
                  <SelectContent>
                    {coManagedMentorOptions.map(m => (
                      <SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
                <p className="text-xs text-orange-600">This is a co-managed client. Select which mentor's net deposit this withdrawal reduces.</p>
              </div>
            )}

            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="rejection_reason">Rejection Reason</Label>
              <Input
                id="rejection_reason"
                value={formData.rejection_reason}
                onChange={(e) => setFormData({ ...formData, rejection_reason: e.target.value })}
                placeholder="Enter reason if rejecting..."
              />
            </div>

            <div className="space-y-2 md:col-span-2">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                placeholder="Add any notes..."
                rows={3}
              />
            </div>
          </div>

          {transaction.screenshot_url && (
            <div className="space-y-2">
              <Label>Screenshot</Label>
              <a
                href={transaction.screenshot_url}
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:text-blue-800 text-sm underline"
              >
                View Screenshot
              </a>
            </div>
          )}

          {/* Commission credited by this transaction — staff, level and amount. */}
          {txCredits.length > 0 && (
            <div className="space-y-2">
              <Label className="text-base font-semibold">Commission Credited</Label>
              <div className="rounded-lg border overflow-hidden">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-gray-50 border-b">
                      <th className="text-left px-3 py-2 font-semibold text-gray-600">Staff</th>
                      <th className="text-center px-3 py-2 font-semibold text-gray-600">Level</th>
                      <th className="text-center px-3 py-2 font-semibold text-gray-600">%</th>
                      <th className="text-right px-3 py-2 font-semibold text-gray-600">Commission</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[...txCredits].sort((a, b) => (a.level || 0) - (b.level || 0)).map((c, i) => (
                      <tr key={c.id || i} className="border-b last:border-0">
                        <td className="px-3 py-2 font-medium text-gray-900">{c.recipient_name || '—'}</td>
                        <td className="px-3 py-2 text-center">L{c.level}</td>
                        <td className="px-3 py-2 text-center text-gray-500">{c.percentage}%</td>
                        <td className={`px-3 py-2 text-right font-bold ${(c.commission_usd || 0) < 0 ? 'text-red-600' : 'text-emerald-700'}`}>
                          ${(c.commission_usd || 0).toFixed(2)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot>
                    <tr className="bg-gray-100 border-t-2 font-bold">
                      <td colSpan={3} className="px-3 py-2 text-gray-700">Total ({txCredits.length})</td>
                      <td className="px-3 py-2 text-right text-emerald-700">
                        ${txCredits.reduce((s, c) => s + (c.commission_usd || 0), 0).toFixed(2)}
                      </td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          )}
        </div>

        <DialogFooter className="flex gap-2">
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button
            variant="destructive"
            onClick={handleReject}
            className="flex items-center gap-2"
          >
            <XCircle className="h-4 w-4" />
            Reject
          </Button>
          <Button
            onClick={handleApprove}
            disabled={isLoadingStudent || (isCoManagedWithdrawal && !withdrawalMentorId)}
            className="bg-emerald-600 hover:bg-emerald-700 flex items-center gap-2 disabled:opacity-50"
          >
            <CheckCircle className="h-4 w-4" />
            {isLoadingStudent ? 'Loading...' : 'Approve'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}